### ISSUE TITLE
More problems running from ipython

### ISSUE THREAD

**Issue by bhaugen** [Punto0/faircoin-nrp#7]
I fixed https://github.com/Punto0/faircoin-nrp/issues/6 locally because I wanted to show you this one:

In [1]: import electrum_fair_nrp

In [2]: electrum_fair_nrp.wallet_path
Out[2]: '/home/bob/.electrum-fair/wallets/default_wallet'

In [3]: electrum_fair_nrp.init()
2016-04-16 07:28:03,593 DEBUG ---------------------------------
2016-04-16 07:28:03,594 DEBUG Starting electrum-fair-nrp
electrum directory /home/bob/.electrum-fair
wallet path /home/bob/.electrum-fair/wallets/default_wallet
[profiler] load_transactions 0.0003

In [4]: [profiler] save_transactions 0.0079

In [4]: electrum_fair_nrp.get_balance()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/home/bob/.virtualenvs/fcx/valuenetwork/faircoin-nrp/<ipython-input-4-733a86e8df57> in <module>()
----> 1 electrum_fair_nrp.get_balance()

/home/bob/.virtualenvs/fcx/valuenetwork/faircoin-nrp/electrum_fair_nrp.pyc in get_balance()
     52 # Returns a tupla with 3 values: Confirmed, Unmature, Unconfirmed

     53 def get_balance():
---> 54     return wallet.get_balance()
     55 
     56 # get the balance for a determined address

NameError: global name 'wallet' is not defined

**Comment by bhaugen** [comment]
I think what happened there is that wallet (and a few other vars) used to be globals before __main__ was changed to init(). Now they are not. So def get_balance(): does not know about wallet.

**Comment by Punto0** [comment]
Yes, added the globals in commit fd2c758af90049609cebde5662edf45a61ee7c32
get_balance() is working now, testing other functions.

**Comment by bhaugen** [comment]
Lookin better...but...

----> 1 electrum_fair_nrp.get_address_history(address)

/home/bob/.virtualenvs/fcx/valuenetwork/faircoin-nrp/electrum_fair_nrp.py in get_address_history(address)
     73 #read the history of an address

     74 def get_address_history(address):
---> 75     return wallet.get_adress_history(address)
     76 
     77 # make a transfer from an adress of the wallet


AttributeError: 'NewWallet' object has no attribute 'get_adress_history'

**Comment by Punto0** [comment]
yeah, a fixing typo, resolved in cf36462b0916e41f06a097bd2c0368e2f9019813
All functions are working for me now
